import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/disabled-draft-mode";
import { VisualEditing } from "next-sanity";

export const metadata: Metadata = {
  title: "Best Buy | Official Online Store | Shop Now & Save",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing />
            </>
          )}
          <main>
            <Header />
            <div className="w-full mx-auto">
              <div className="max-w-[1600px] mx-auto">{children}</div>
            </div>
          </main>

          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
